version: 0.2

env:
  variables:
    AQUA_KEY: "HUhAs50j7A6VI6CkSojYwR"
    AQUA_SECRET: "EkMeRiVwCAOkZ3iUv6EbAyaaKoIG8fNdxEV"
    TRIVY_RUN_AS_PLUGIN: "aqua"
    trivyVersion: "0.35.0"
    #DOCKER_REGISTRY: "000000000000.dkr.ecr.us-west-2.amazonaws.com"
    #IMAGE_TAG: "image-${CODEBUILD_RESOLVED_SOURCE_VERSION}"
    AQUA_URL: "https://api.asia-2.supply-chain.cloud.aquasec.com"
    CSPM_URL: "https://asia-2.api.cloudsploit.com"


phases:
  build: 
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY/$IMAGE_TAG"
      - echo "Downloading and running Trivy"
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v${trivyVersion}
      - ./trivy fs --security-checks config,vuln,secret .
      - docker build -t "$DOCKER_REGISTRY/$IMAGE_TAG" .
      - echo "Pushing Docker image to the registry..."
      - #$(aws ecr get-login --no-include-email --region us-west-2)
      - #docker push "$DOCKER_REGISTRY/$IMAGE_TAG"

artifacts:
  type: "image"
  files:
    - "$DOCKER_REGISTRY/$IMAGE_TAG"
